<?php
$resources['Ask.fm']       = 'https://ask.fm/{{username}}';
$resources['Behance']      = 'https://www.behance.net/{{username}}';
$resources['Bitbucket']    = 'https://bitbucket.org/{{username}}/';
$resources['Blogspot']     = 'https://{{username}}.blogspot.com/';
$resources['Boostlog']     = 'https://boostlog.io/_{{username}}/';
$resources['CodePen']      = 'https://codepen.io/{{username}}';
$resources['DeviantArt']   = 'https://www.deviantart.com/{{username}}';
$resources['Dribbble']     = 'https://dribbble.com/{{username}}';
$resources['Drive2']       = 'https://www.drive2.ru/users/{{username}}/';
$resources['Etsy']         = 'https://www.etsy.com/shop/{{username}}';
$resources['Freelanchunt'] = 'https://freelancehunt.com/freelancer/{{username}}.html';
$resources['GitHub']       = 'https://github.com/{{username}}';
$resources['GitHubGist']   = 'https://gist.github.com/{{username}}';
$resources['Goodreads']    = 'https://www.goodreads.com/{{username}}';
$resources['Habr']         = 'https://habr.com/users/{{username}}/';
$resources['Last.fm']      = 'https://www.last.fm/user/{{username}}';
$resources['LiveJournal']  = 'https://{{username}}.livejournal.com/';
$resources['Main']         = 'https://main.community/u/{{username}}';
$resources['Pikabu']       = 'https://pikabu.ru/@{{username}}';
$resources['ProductHunt']  = 'https://www.producthunt.com/@{{username}}';
$resources['Replit']       = 'https://replit.com/@{{username}}';
$resources['SlideShare']   = 'https://www.slideshare.net/{{username}}';
$resources['Snapchat']     = 'https://www.snapchat.com/add/{{username}}';
$resources['Spotify']      = 'https://open.spotify.com/user/{{username}}';
$resources['TikTok']       = 'https://www.tiktok.com/@{{username}}';
$resources['Tumblr']       = 'https://www.tumblr.com/{{username}}';
$resources['Vimeo']        = 'https://vimeo.com/{{username}}';
$resources['Wattpad']      = 'https://www.wattpad.com/user/{{username}}';
$resources['YouTube']      = 'https://www.youtube.com/@{{username}}';

define('RESOURCES', $resources);